version: "3.8"

services:
  db:
    image: mysql:8.0.31
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_USER: crypto
      MYSQL_PASSWORD: crypto

volumes:
  db_data: