spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crypto?useUnicode=yes&serverTimezone=UTC&characterEncoding=UTF-8
    username: crypto
    password: crypto

  jpa:
    hibernate:
      ddl-auto: update


telegram:
  token: TOKEN
  base-url: "https://api.telegram.org/bot"

crypto:
  fixedRate: 10000 # In seconds
  maxUserPool: 1000


